# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    # (let nixos-hardware =
    #        builtins.fetchTarball
    #          https://github.com/NixOS/nixos-hardware/archive/master.tar.gz;
    #  in "${nixos-hardware}/dell/xps/13-9370")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernel.sysctl = { "fs.inotify.max_user_watches" = 524288; };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  ## CPU
  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = true;

  ## SSDs
  services.fstrim.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/771d96e7-fc49-492e-b921-65a2e09f5917";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/14E0-8688";
      fsType = "vfat";
    };

  fileSystems."/mnt/projects" =
    { device = "/dev/disk/by-uuid/0844c52a-b12c-4688-934d-a446c9a0ca2e";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6c392ff0-4b5d-43cd-ac67-5b5053af29f2"; }
    ];
}
